server:
  port: 8889
  contextPath: /auth

#security:
#  user:
#    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/